function [acceptance_rate] = compute_acceptance_rate(x_t, y_t, alpha)
    
    %acceptance_rate = (compute_target_llh(y_t).* ...
    %    proposal_pdf_unif_log_likelihood(x_t, y_t, alpha))./...
    %    (proposal_pdf_unif_log_likelihood(y_t, x_t, alpha).*...
    %    compute_target_llh(x_t));
    
    acceptance_rate = (log(compute_target_llh(y_t)) + ...
        log(proposal_pdf_unif_log_likelihood(x_t, y_t, alpha)) - ...
        log(proposal_pdf_unif_log_likelihood(y_t, x_t, alpha)) -...
        log(compute_target_llh(x_t)));
    
end